### ISSUE TITLE
all2vcf mummer index out of range

### ISSUE THREAD

**Issue by johnstonmj** [MatteoSchiavinato/all2vcf#6]
all2vcf mummer instructions indicate:

> Note: show-snps must be run with tab-delimited output: `show-snps -T`

However, I still encountered list index out of range, where all2vcf attempts to access empty columns in the `show-snvs -T` output.
I had to include the option `-l` (output sequence lengths) as well to align the snow-snps output with the expected columns of all2vcf.

Running 
`show-snps -C -r -l -T`

allowed
```
all2vcf mummer \
    --snps output.snvs \
    --reference refrence.fasta \
    --input-header \
    --output-header > ouotput.snvs.vcf
```
to run successfully.

An update to the all2vcf mummer instructions would probably fix this.

Thanks :)

Original error message:

```
Error:
Traceback (most recent call last):
  File "/home/user/software/all2vcf/src/mummer", line 370, in <module>
    Vcf_lines = [ convert_snps_to_vcf(line) for line in Lines ]
  File "/home/user/software/all2vcf/src/mummer", line 370, in <listcomp>
    Vcf_lines = [ convert_snps_to_vcf(line) for line in Lines ]
  File "/home/user/software/all2vcf/src/mummer", line 63, in convert_snps_to_vcf
    scaffold = lst[10]
IndexError: list index out of range
```

**Comment by MatteoSchiavinato** [comment]
Thanks! May I ask you what version of mummer you're using? Perhaps it has to do with that. I developed this piece of code many years ago, and haven't really maintained it so it is a bit obsolete...

**Comment by johnstonmj** [comment]
Of course! Just trying to leave breadcrumbs in case anyone else wants to use your tool!

I encountered this error while running mummer=3.23 installed via bioconda channel in conda.

Thanks again

**Comment by MatteoSchiavinato** [comment]
One thing I just remembered is that show-snps parameters are sequential, that is, they are applied in the order you declare them. As far as I remember they suggest -cLTr as a combination (I may be wrong).
